import { useState, useEffect } from 'react'
import './App.css'

function parseCSV(text) {
  const lines = text.trim().split('\n')
  const headers = lines[0].split(',')
  return lines.slice(1).map(line => {
    const values = line.split(',')
    const obj = {}
    headers.forEach((header, i) => {
      let val = values[i]
      if (val && val.startsWith('"') && val.endsWith('"')) {
        val = val.slice(1, -1)
      }
      if (val && !isNaN(val) && val !== '') {
        obj[header] = parseFloat(val)
      } else if (val === '' || val === 'None') {
        obj[header] = null
      } else {
        obj[header] = val
      }
    })
    return obj
  })
}

function formatValue(val, unit, pct) {
  if (val === null || val === undefined) return '—'
  let str = ''
  if (unit === '£') str = `£${val.toLocaleString()}`
  else if (unit === 'bn') str = `£${val}bn`
  else if (unit === '%') str = `${val}%`
  else if (unit === 'k') str = `${val.toLocaleString()}k`
  else if (unit === 'm') str = `${val}m`
  else str = `${val}${unit}`
  if (pct !== null && pct !== undefined) str += ` (${pct}%)`
  return str
}

function formatDiff(val, unit) {
  if (val === null || val === undefined) return '—'
  const sign = val >= 0 ? '+' : ''
  if (unit === '£') return `${sign}£${val}`
  if (unit === 'bn') return `${sign}£${val}bn`
  if (unit === '%') return `${sign}${val}pp`
  if (unit === 'k') return `${sign}${val}k`
  if (unit === 'm') return `${sign}${val}m`
  return `${sign}${val}${unit}`
}

function StatusDot({ status }) {
  return <span className={`status-dot ${status}`}></span>
}

function ComparisonTable({ data }) {
  return (
    <div className="comparison-table-wrapper">
      <table className="comparison-table">
        <thead>
          <tr>
            <th>Metric</th>
            <th>RF</th>
            <th>PE</th>
            <th>Difference</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {data.map((row, i) => (
            <tr key={i}>
              <td className="metric-name">
                <div>{row.metric}</div>
                {row.description && <div className="metric-description">{row.description}</div>}
              </td>
              <td className="rf-value">
                {formatValue(row.rf_value, row.rf_unit, row.rf_pct)}
                {row.rf_year && <div className="year-label">{row.rf_year}</div>}
              </td>
              <td className="pe-value">
                {formatValue(row.pe_value, row.pe_unit, row.pe_pct)}
                {row.pe_year && <div className="year-label">{row.pe_year}</div>}
              </td>
              <td className={`diff-value ${row.diff_value >= 0 ? 'positive' : 'negative'}`}>
                {formatDiff(row.diff_value, row.rf_unit)}
              </td>
              <td className="status-cell"><StatusDot status={row.status} /></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function ElementsChart({ elements }) {
  const maxVal = Math.max(...elements.map(e => e.expenditure_bn))
  return (
    <div className="elements-section">
      <div className="elements-chart">
        {elements.map((el, i) => (
          <div key={i} className="element-row">
            <span className="element-label">{el.element}</span>
            <div className="bar-container">
              <div className="bar" style={{ width: `${(el.expenditure_bn / maxVal) * 100}%` }} />
              <span className="bar-value">£{el.expenditure_bn}bn ({el.pct_gross}%)</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// RF Recommendations - loaded from CSV (generated by rf_pe_uc_comparison.py)

// Hardcoded recommendations data for the detailed table
const RF_RECOMMENDATIONS_DISPLAY = [
  {
    id: 1,
    recommendation: "Extend MIF (Minimum Income Floor) startup period to 24 months",
    description: "Currently self-employed UC claimants get 12-month exemption from the Minimum Income Floor before assumed earnings (minimum wage × 35 hours) apply. RF proposes doubling to 24 months to help businesses establish.",
    status: "can",
    pe_position: "CAN MODEL. PE has uc_mif_applies.py with in_startup_period parameter. Could add parameter for startup length and model cost of extension."
  },
  {
    id: 2,
    recommendation: "Apply MIF after 3-month rolling average",
    description: "Instead of applying MIF monthly, use 3-month rolling average of self-employment earnings. Smooths volatility for gig workers and seasonal businesses.",
    status: "partial",
    pe_position: "PARTIAL. PE uses definition_period = YEAR. Could approximate annual averaging effect, but cannot model true monthly rolling calculation."
  },
  {
    id: 3,
    recommendation: "Align MIF expected hours with claimant commitments",
    description: "MIF currently assumes 35 hours/week for all. RF proposes aligning with individual's agreed work commitment (e.g., 16 hours for parents with young children).",
    status: "can",
    pe_position: "CAN MODEL. PE has default_expected_hours.yaml (35 hrs). Could parameterize by claimant circumstances and model distributional impacts."
  },
  {
    id: 4,
    recommendation: "Review MIF exemption for carers",
    description: "Carers caring 35+ hours/week are MIF-exempt. RF wants review of whether threshold is appropriate and if exemption should extend to lower caring hours.",
    status: "can",
    pe_position: "CAN MODEL. PE can adjust carer exemption thresholds and model cost/distributional effects of expanding exemption criteria."
  },
  {
    id: 5,
    recommendation: "Pay UC fortnightly or 4-weekly",
    description: "UC currently paid monthly, misaligned with many workers' pay cycles. RF proposes more frequent payment options to help budgeting.",
    status: "partial",
    pe_position: "LIMITED. PE is annual model - cannot capture payment frequency effects on household budgeting/cashflow. Could model 4-weekly assessment periods' annual impact."
  },
  {
    id: 6,
    recommendation: "Reduce 5-week wait",
    description: "New claimants wait 5 weeks for first payment (1 month assessment + 1 week processing). RF proposes shortening this gap.",
    status: "cannot",
    pe_position: "CANNOT MODEL. This is administrative timing - PE models annual entitlements, not payment timing or cashflow within year."
  },
  {
    id: 7,
    recommendation: "Improve Advance Payments access",
    description: "Claimants can get advances during 5-week wait but must repay. RF wants better awareness, easier access, and more favorable repayment terms.",
    status: "cannot",
    pe_position: "CANNOT MODEL. Advances are loans repaid from future UC - PE doesn't model debt/repayment dynamics or take-up behavior."
  },
  {
    id: 8,
    recommendation: "Abolish Benefit Cap for those meeting work requirements",
    description: "£22,020/year cap on total benefits. RF proposes exempting those meeting work conditionality (attending appointments, job searching, etc.).",
    status: "partial",
    pe_position: "PARTIAL. PE models benefit cap (benefit_cap.py) but doesn't track conditionality compliance. Could model full abolition or exemptions by measurable characteristics."
  },
  {
    id: 9,
    recommendation: "Extend childcare run-on to 3 months",
    description: "UC childcare element stops when employment ends. RF proposes 3-month continuation to help parents search for new work without losing childcare.",
    status: "can",
    pe_position: "CAN MODEL. PE has uc_childcare_element.py. Could add run-on parameter and model cost of extending support post-employment."
  },
  {
    id: 10,
    recommendation: "Improve upfront childcare cost support",
    description: "UC reimburses childcare (85% up to caps) in arrears, but parents need upfront payment. RF wants better access to Flexible Support Fund grants for deposits/first months.",
    status: "cannot",
    pe_position: "CANNOT MODEL. FSF is discretionary, locally-administered grant. PE models entitlement rules, not discretionary/administrative support."
  },
  {
    id: 11,
    recommendation: "Better integrate UC with Tax-Free Childcare",
    description: "UC childcare (85% subsidy) and TFC (20% top-up) can't be combined. RF wants clearer guidance and potentially allowing combination for different children.",
    status: "partial",
    pe_position: "PARTIAL. PE models both UC childcare and TFC separately. Could model allowing combination, but not behavioral responses to information/guidance changes."
  },
  {
    id: 12,
    recommendation: "Promote benefits calculators for entitlement checks",
    description: "RF recommends UC claimants use independent benefits calculators to verify entitlement and catch DWP errors.",
    status: "can",
    pe_position: "PE DOES THIS. This IS PolicyEngine's core function - calculating benefit entitlements. PE could be specifically promoted for this use case."
  },
  {
    id: 13,
    recommendation: "Simplify Mandatory Reconsideration process",
    description: "MR is first step to challenge UC decisions. RF wants simpler forms, clearer deadlines, better DWP communication throughout.",
    status: "cannot",
    pe_position: "CANNOT MODEL. This is administrative process reform - PE models policy rules, not appeals/disputes infrastructure."
  },
  {
    id: 14,
    recommendation: "Improve DWP communication and transparency",
    description: "RF wants clearer UC statements, better explanation of calculations, proactive notification of changes affecting awards.",
    status: "cannot",
    pe_position: "CANNOT MODEL. Communication quality is operational - PE models what entitlements should be, not how they're communicated."
  },
  {
    id: 15,
    recommendation: "Train work coaches on self-employment support",
    description: "Work coaches often lack expertise in self-employment. RF wants specialized training and access to business support resources.",
    status: "cannot",
    pe_position: "CANNOT MODEL. Staff training is operational/cultural change outside microsimulation scope."
  },
  {
    id: 16,
    recommendation: "Develop DWP digital self-employment tools",
    description: "RF proposes DWP-provided apps/tools to help self-employed track income, understand MIF, and report earnings accurately.",
    status: "cannot",
    pe_position: "CANNOT MODEL. Digital infrastructure development is outside microsimulation scope."
  }
]

function RecommendationsTable() {
  const [isExpanded, setIsExpanded] = useState(false)

  const getStatusIcon = (status) => {
    if (status === 'can') return '✅'
    if (status === 'partial') return '⚠️'
    return '❌'
  }

  return (
    <div className="recommendations-table-wrapper">
      <table className="recommendations-table detailed">
        <thead>
          <tr className="table-header-toggle" onClick={() => setIsExpanded(!isExpanded)}>
            <th colSpan={4} className="expandable-header">
              <div className="expandable-header-content">
                <span className={`table-expand-icon ${isExpanded ? 'open' : ''}`}>▶</span>
                <span className="expandable-header-text">
                  {isExpanded ? 'Hide recommendations' : 'Show 16 recommendations'}
                </span>
              </div>
            </th>
          </tr>
          {isExpanded && (
            <tr className="column-headers">
              <th className="col-id">#</th>
              <th className="col-rec">Recommendation</th>
              <th className="col-desc">Detailed Description</th>
              <th className="col-pe">PolicyEngine UK Position</th>
            </tr>
          )}
        </thead>
        {isExpanded && (
          <tbody>
            {RF_RECOMMENDATIONS_DISPLAY.map((row) => (
              <tr key={row.id} className="rec-row">
                <td className="rec-id">{row.id}</td>
                <td className="rec-name">{row.recommendation}</td>
                <td className="rec-desc">{row.description}</td>
                <td className="rec-pe-position">
                  <span className="status-icon">{getStatusIcon(row.status)}</span>
                  {row.pe_position}
                </td>
              </tr>
            ))}
          </tbody>
        )}
      </table>
    </div>
  )
}

function App() {
  const [metadata, setMetadata] = useState(null)
  const [comparison, setComparison] = useState([])
  const [elements, setElements] = useState([])
  const [policyImpacts, setPolicyImpacts] = useState([])
  const [recommendations, setRecommendations] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    async function loadData() {
      try {
        const [metaRes, compRes, elemRes, policyRes, recRes] = await Promise.all([
          fetch('/data/metadata.csv'),
          fetch('/data/comparison.csv'),
          fetch('/data/uc_elements.csv'),
          fetch('/data/policy_impacts.csv'),
          fetch('/data/recommendations.csv')
        ])
        const [metaText, compText, elemText, policyText, recText] = await Promise.all([
          metaRes.text(), compRes.text(), elemRes.text(), policyRes.text(), recRes.text()
        ])
        setMetadata(parseCSV(metaText)[0])
        setComparison(parseCSV(compText))
        setElements(parseCSV(elemText))
        setPolicyImpacts(parseCSV(policyText))
        setRecommendations(parseCSV(recText))
        setLoading(false)
      } catch (err) {
        setError(err.message)
        setLoading(false)
      }
    }
    loadData()
  }, [])

  if (loading) return <div className="loading">Loading data...</div>
  if (error) return <div className="error">Error: {error}</div>

  const benefitCap = policyImpacts.filter(p => p.category === 'benefit_cap')
  const selfEmp = policyImpacts.find(p => p.category === 'self_employment')
  const carers = policyImpacts.find(p => p.category === 'carers')

  return (
    <div className="app">
      <header className="title-row">
        <div className="title-row-inner">
          <h1>Resolution Foundation vs PolicyEngine: Universal Credit comparison</h1>
        </div>
      </header>

      <main className="main-content">
        <p className="dashboard-intro">
          This dashboard compares Universal Credit statistics from the Resolution Foundation's
          <a href="https://www.resolutionfoundation.org/app/uploads/2026/01/Listen-and-learn.pdf" target="_blank" rel="noopener noreferrer">"Listen and Learn" report</a> (January 2026)
          with <a href="https://policyengine.org" target="_blank" rel="noopener noreferrer">PolicyEngine UK</a> microsimulation estimates.
          The dashboard includes: (1) a comparison of key UC metrics between RF's analysis and PE's estimates,
          (2) PolicyEngine's estimates of benefit cap impacts and UC claimant demographics,
          (3) a breakdown of UC expenditure by element, and
          (4) an assessment of which RF policy recommendations can be modelled using PolicyEngine's tax-benefit microsimulation.
        </p>

        <section className="section">
          <h2>PolicyEngine vs RF comparison</h2>
          <p className="section-description">
            The table below compares key Universal Credit statistics between the Resolution Foundation's
            administrative data analysis and PolicyEngine UK's microsimulation estimates using the
            enhanced Family Resources Survey. Metrics include UC caseload, expenditure, average awards,
            and demographic breakdowns. The colour indicators show how closely PE's estimates align with RF's figures:
            green indicates close agreement (&lt;10% difference), yellow indicates moderate divergence (10-20%),
            and red indicates larger discrepancies (&gt;20%) that may warrant further investigation.
          </p>
          <ComparisonTable data={comparison} />
          <div className="table-legend">
            <span className="legend-item"><StatusDot status="close_match" /> &lt;10% difference</span>
            <span className="legend-item"><StatusDot status="moderate_diff" /> 10-20% difference</span>
            <span className="legend-item"><StatusDot status="large_discrepancy" /> &gt;20% difference</span>
          </div>
        </section>

        <section className="section">
          <h2>Benefit cap & UC demographics</h2>
          <p className="section-description">
            The benefit cap limits total household benefits to £22,020/year (£25,323 in London) for couples and families,
            and £14,753 (£16,967 in London) for single adults. PolicyEngine UK estimates the impact of this cap and
            key UC claimant demographics below. The Minimum Income Floor (MIF) affects self-employed claimants by
            assuming minimum wage earnings, while carers receiving Carer's Allowance may qualify for the UC carer element.
          </p>
          <div className="key-metrics-row">
            <div className="key-metric highlighted">
              <div className="metric-label">Total cap reduction</div>
              <div className="metric-number">
                £{benefitCap.find(p => p.metric === 'Total cap reduction')?.value}m
              </div>
              <div className="metric-desc">Annual amount cut from household benefits due to the benefit cap</div>
            </div>
            <div className="key-metric">
              <div className="metric-label">Households capped</div>
              <div className="metric-number">
                {benefitCap.find(p => p.metric === 'Households capped')?.value}k
              </div>
              <div className="metric-desc">Households with UC reduced by benefit cap</div>
            </div>
            <div className="key-metric">
              <div className="metric-label">Self-employed on UC</div>
              <div className="metric-number">{selfEmp?.value}m</div>
              <div className="metric-desc">Self-employed individuals receiving UC</div>
            </div>
            <div className="key-metric">
              <div className="metric-label">Carers on UC</div>
              <div className="metric-number">{carers?.value}m</div>
              <div className="metric-desc">Carers receiving Universal Credit</div>
            </div>
          </div>
        </section>

        <section className="section">
          <h2>UC elements breakdown</h2>
          <p className="section-description">
            Universal Credit is made up of several elements: a standard allowance (based on age and relationship status),
            plus additional amounts for housing costs, children, disability, childcare, and caring responsibilities.
            The chart below shows estimated annual expenditure by element after the 55% taper rate has been applied
            to reduce awards based on household earnings.
          </p>
          <ElementsChart elements={elements} />
        </section>

        <section className="section">
          <h2>Resolution Foundation "Listen and Learn" (January 2026)</h2>
          <p className="section-description">
            The Resolution Foundation's <a href="https://www.resolutionfoundation.org/app/uploads/2026/01/Listen-and-learn.pdf" target="_blank" rel="noopener noreferrer">"Listen and Learn"</a> report
            examines how Universal Credit is working for claimants, drawing on interviews with UC recipients, DWP staff,
            and analysis of administrative data. The report identifies key pain points including the 5-week wait for
            first payment, the Minimum Income Floor's impact on self-employed workers, childcare cost barriers, and
            the benefit cap's effect on larger families. RF proposes 16 recommendations with an estimated total cost
            of ~£400m in one-off implementation costs (DEL) plus £700-900m in ongoing annual benefit spending (AME).
            Below we assess which recommendations can be modelled using PolicyEngine UK's microsimulation capabilities.
          </p>
          <RecommendationsTable />
        </section>
      </main>
    </div>
  )
}

export default App
